# Generated by Django 4.1.7 on 2023-03-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appFName', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('appLName', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('appUCID', models.CharField(default='', max_length=100, verbose_name='UCID')),
                ('course', models.CharField(choices=[('ENG', 'ENGG200'), ('ENG', 'ENGG202'), ('ENG', 'ENGG204'), ('ENG', 'ENGG209'), ('ENG', 'ENGG212'), ('ENG', 'ENGG213'), ('ENG', 'ENGG225'), ('ENG', 'ENGG317'), ('ENG', 'ENGG349'), ('ENG', 'ENGG481'), ('ENG', 'ENGG501'), ('ENG', 'ENGG504'), ('ANT', 'ANTH313'), ('ANT', 'ANTH311'), ('ANT', 'ANTH320'), ('ANT', 'ANTH343'), ('ANT', 'ANTH346'), ('ANT', 'ANTH355'), ('ANT', 'ANTH412'), ('ANT', 'ANTH425'), ('KNE', 'KNES259'), ('KNE', 'KNES260'), ('KNE', 'KNES323'), ('KNE', 'KNES351'), ('KNE', 'KNES373'), ('KNE', 'KNES411'), ('KNE', 'KNES413'), ('KNE', 'KNES464'), ('KNE', 'KNES465'), ('GEO', 'GEOG204'), ('GEO', 'GEOG254'), ('GEO', 'GEOG303'), ('GEO', 'GEOG310'), ('GEO', 'GEOG324'), ('GEO', 'GEOG328'), ('GEO', 'GEOG330'), ('GEO', 'GEOG390'), ('GEO', 'GEOG412'), ('GEO', 'GEOG426')], default='', max_length=100, verbose_name='course')),
                ('major', models.CharField(default='', max_length=100, verbose_name='major')),
                ('year', models.CharField(default='', max_length=100, verbose_name='year')),
                ('ques1', models.TextField(default='', verbose_name='ques1')),
                ('ques2', models.TextField(default='', verbose_name='ques2')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('professorRating', models.CharField(max_length=100, verbose_name='Will you take this course with this professor again?')),
                ('professorN', models.CharField(max_length=100, verbose_name='Professors Name')),
                ('courseComment', models.TextField(verbose_name='Comment')),
                ('commenterName', models.CharField(max_length=100, verbose_name='Commenters Name')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profID', models.CharField(max_length=100, verbose_name='Professors ID')),
                ('profName', models.CharField(max_length=100, verbose_name='Professors Name')),
                ('profEmailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('profPhoneNumber', models.TextField(verbose_name='PhoneNumber')),
                ('profAbout', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorID', models.CharField(max_length=100, verbose_name='Tutors ID')),
                ('tutorName', models.CharField(max_length=100, verbose_name='Tutors Name')),
                ('tutorEmailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('tutorPhoneNumber', models.TextField(verbose_name='PhoneNumber')),
                ('tutorAbout', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('courseSummary', models.TextField(blank=True)),
                ('courseProfessors', models.ManyToManyField(blank=True, to='stuhub.professor')),
                ('courseTutors', models.ManyToManyField(blank=True, to='stuhub.tutor')),
            ],
        ),
    ]
