# Generated by Django 4.1.7 on 2023-03-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('professorRating', models.CharField(max_length=100, verbose_name='Prof Rating 1-10')),
                ('professorN', models.CharField(max_length=100, verbose_name='Professors Name')),
                ('courseComment', models.TextField(verbose_name='Comment')),
                ('commenterName', models.CharField(max_length=100, verbose_name='Commenters Name')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profName', models.CharField(max_length=100, verbose_name='Professors Name')),
                ('profEmailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('profPhoneNumber', models.TextField(verbose_name='PhoneNumber')),
                ('profAbout', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.CharField(max_length=100, verbose_name='Tutors Name')),
                ('tutorEmailAddress', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('tutorPhoneNumber', models.TextField(verbose_name='PhoneNumber')),
                ('tutorAbout', models.TextField(verbose_name='About')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
                ('courseSummary', models.TextField(blank=True)),
                ('courseComments', models.ManyToManyField(blank=True, to='stuhub.comment')),
                ('courseProfessors', models.ManyToManyField(blank=True, to='stuhub.professor')),
                ('courseTutors', models.ManyToManyField(blank=True, to='stuhub.tutor')),
            ],
        ),
    ]
