# Generated by Django 4.1.7 on 2023-03-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseComments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
