# Generated by Django 4.1.7 on 2023-03-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseComments',
            field=models.ManyToManyField(blank=True, to='stuhub.comment'),
        ),
    ]
