# Generated by Django 4.1.7 on 2023-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0004_course_coursecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='profID',
            field=models.CharField(blank=True, max_length=100, verbose_name='Professors ID'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutorID',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tutors ID'),
        ),
    ]
