# Generated by Django 4.1.7 on 2023-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0005_professor_profid_tutor_tutorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='profID',
            field=models.CharField(max_length=100, verbose_name='Professors ID'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutorID',
            field=models.CharField(max_length=100, verbose_name='Tutors ID'),
        ),
    ]
