# Generated by Django 4.1.7 on 2023-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0007_remove_course_coursecomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='professorRating',
            field=models.CharField(max_length=100, verbose_name='Will you take this course with this professor again?'),
        ),
    ]
