# Generated by Django 4.1.7 on 2023-03-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0008_alter_comment_professorrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100, verbose_name='Course Name')),
            ],
        ),
    ]
