# Generated by Django 4.1.7 on 2023-03-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0008_alter_comment_professorrating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appFName",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "appLName",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                ("appUCID", models.CharField(max_length=100, verbose_name="UCID")),
                ("course", models.CharField(max_length=100, verbose_name="course")),
                ("major", models.CharField(max_length=100, verbose_name="major")),
                ("year", models.CharField(max_length=100, verbose_name="year")),
            ],
        ),
    ]
