# Generated by Django 4.1.7 on 2023-03-22 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuhub', '0009_courserequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseRequests',
            new_name='CourseRequest',
        ),
    ]
