# Generated by Django 4.1.7 on 2023-03-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0009_applicant"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="ques1",
            field=models.TextField(default="", verbose_name="ques1"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="ques2",
            field=models.TextField(default="", verbose_name="ques2"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="appFName",
            field=models.CharField(
                default="", max_length=100, verbose_name="First Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="appLName",
            field=models.CharField(
                default="", max_length=100, verbose_name="Last Name"
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="appUCID",
            field=models.CharField(default="", max_length=100, verbose_name="UCID"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="course",
            field=models.CharField(default="", max_length=100, verbose_name="course"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="major",
            field=models.CharField(default="", max_length=100, verbose_name="major"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="year",
            field=models.CharField(default="", max_length=100, verbose_name="year"),
        ),
    ]
