# Generated by Django 4.1.7 on 2023-03-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0010_applicant_ques1_applicant_ques2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="transcript",
            field=models.FileField(
                default=0,
                upload_to="applications/transcripts/",
                verbose_name="transcript",
            ),
        ),
    ]
