# Generated by Django 4.1.7 on 2023-03-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0011_applicant"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="id",),
        migrations.AlterField(
            model_name="applicant",
            name="appUCID",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, verbose_name="UCID"
            ),
        ),
    ]
