# Generated by Django 4.1.7 on 2023-03-27 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0011_applicant_transcript"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="ques2",),
    ]
