# Generated by Django 4.1.7 on 2023-03-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0012_remove_applicant_id_alter_applicant_appucid"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="appFName",),
        migrations.RemoveField(model_name="applicant", name="appLName",),
        migrations.AddField(
            model_name="applicant",
            name="appEmail",
            field=models.EmailField(default="", max_length=100, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="applicant",
            name="appFullName",
            field=models.CharField(
                default="", max_length=100, verbose_name="Full Name"
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="appPhoneNum",
            field=models.IntegerField(default=0, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="appUCID",
            field=models.CharField(
                max_length=10, primary_key=True, serialize=False, verbose_name="UCID"
            ),
        ),
    ]
