# Generated by Django 4.1.7 on 2023-03-27 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0012_remove_applicant_ques2"),
    ]

    operations = [
        migrations.RemoveField(model_name="applicant", name="transcript",),
        migrations.AddField(
            model_name="applicant",
            name="ques2",
            field=models.TextField(default="", verbose_name="ques2"),
        ),
    ]
