# Generated by Django 4.1.7 on 2023-03-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stuhub", "0013_remove_applicant_transcript_applicant_ques2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="course",
            field=models.CharField(
                choices=[
                    ("ENG", "ENGG200"),
                    ("ENG", "ENGG202"),
                    ("ENG", "ENGG204"),
                    ("ENG", "ENGG209"),
                    ("ENG", "ENGG212"),
                    ("ENG", "ENGG213"),
                    ("ENG", "ENGG225"),
                    ("ENG", "ENGG317"),
                    ("ENG", "ENGG349"),
                    ("ENG", "ENGG481"),
                    ("ENG", "ENGG501"),
                    ("ENG", "ENGG504"),
                    ("ANT", "ANTH313"),
                    ("ANT", "ANTH311"),
                    ("ANT", "ANTH320"),
                    ("ANT", "ANTH343"),
                    ("ANT", "ANTH346"),
                    ("ANT", "ANTH355"),
                    ("ANT", "ANTH412"),
                    ("ANT", "ANTH425"),
                    ("KNE", "KNES259"),
                    ("KNE", "KNES260"),
                    ("KNE", "KNES323"),
                    ("KNE", "KNES351"),
                    ("KNE", "KNES373"),
                    ("KNE", "KNES411"),
                    ("KNE", "KNES413"),
                    ("KNE", "KNES464"),
                    ("KNE", "KNES465"),
                    ("GEO", "GEOG204"),
                    ("GEO", "GEOG254"),
                    ("GEO", "GEOG303"),
                    ("GEO", "GEOG310"),
                    ("GEO", "GEOG324"),
                    ("GEO", "GEOG328"),
                    ("GEO", "GEOG330"),
                    ("GEO", "GEOG390"),
                    ("GEO", "GEOG412"),
                    ("GEO", "GEOG426"),
                ],
                default="",
                max_length=100,
                verbose_name="course",
            ),
        ),
    ]
